const express = require('express')
const upload = require('../middlewares/multer')
const {addDoctor,adminLogin, allDoctors, appointmentsAdmin, appointmentCancelled, adminDashboard }= require('../controllers/admin.controller')
const {authAdmin} = require('../middlewares/authAdmin')
const { changeAvailability } = require('../controllers/doctor.controller')
const adminRoutes = express.Router()
adminRoutes.post('/add-doctor',authAdmin,upload.single('image'),addDoctor)
adminRoutes.post('/login',adminLogin)
adminRoutes.post('/all-doctors',authAdmin,allDoctors)
adminRoutes.post('/change-availability',authAdmin,changeAvailability)
adminRoutes.get('/appointments',authAdmin,appointmentsAdmin)
adminRoutes.post('/cancel-appointment',authAdmin,appointmentCancelled)
adminRoutes.get('/dashboard',authAdmin,adminDashboard)
module.exports = adminRoutes