const express = require('express')
const { userRegister, userLogin, getProfile, updateProfile, bookAppointment, listAppointment, cancelAppointment, paymentRazorpay, verifyRazorpay } = require('../controllers/user.controller')
const upload  = require('../middlewares/multer')
const { authUser } = require('../middlewares/authUser')
const userRoutes = express.Router()
userRoutes.post('/register',userRegister)
userRoutes.post('/login',userLogin)
userRoutes.get('/get-profile',authUser,getProfile)
userRoutes.post('/update-profile',upload.single('image'),authUser,updateProfile)
userRoutes.post('/book-appointment',authUser,bookAppointment)
userRoutes.get('/appointments',authUser,listAppointment)
userRoutes.post('/cancel-appointment',authUser,cancelAppointment)
userRoutes.post('/payment-razorpay',authUser,paymentRazorpay)
userRoutes.post('/verifyRazorpay',authUser,verifyRazorpay)
module.exports = userRoutes
